### ISSUE TITLE
Bnp Parisbas FORTIS

### ISSUE THREAD

**Issue by JokerLand** [Binnette/homebank-converter#4]
Hello, 

I post here my file with data export from bnp parisbas fortis. :)
[bnpParisBasFortis.zip](https://github.com/Binnette/homebank-converter/files/1250133/bnpParisBasFortis.zip)

Thank you

**Comment by Binnette** [comment]
Hi @JokerLand, i finally added support for "BNP Paribas Fortis" files (fixed by 839567693d821b4b4862372656ceace3a03eb78e)

Please feel free to:
- test it/use it
- report any bug
- ask for improvements

In fact homebank-converter is able to identify "paymode" by analysing "memo". For exemple, in your file I set paymode to 6 (debit card) when memo start with "PAIEMENT PAR CARTE DE BANQUE".

So if you give me other files of your bank, i will try to guess more "paymode".
Edit: i've just added paymode list in README :wink:
